# Generated by Django 4.1 on 2022-08-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=50)),
                ('date', models.DateField()),
                ('room', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('idle', 'idle'), ('reserved', 'reserved'), ('cancelled', 'cancelled')], default='idle', max_length=50)),
                ('customer', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_api.customer')),
                ('event', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_api.event')),
            ],
        ),
    ]
