# Generated by Django 4.1 on 2022-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_event_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
