# Generated by Django 4.1 on 2022-08-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_api.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_api.event'),
        ),
    ]
