# Generated by Django 4.1 on 2022-08-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0004_remove_event_date_remove_event_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2022-09-01'),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_api.room'),
        ),
    ]
