# Generated by Django 4.1 on 2022-08-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0005_remove_booking_name_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
