# Generated by Django 4.1 on 2022-08-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0006_remove_event_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
