# Generated by Django 4.1 on 2022-08-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0007_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
