# Generated by Django 4.1 on 2022-08-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0009_event_available_spaces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='available_spaces',
            new_name='available_places',
        ),
    ]
